"""
Inject incremental rows into the upstream PostgreSQL data mart for testing
strata's watermark-bounded incremental ingestion against the production-
shape schema described in ``examples/sample_datamart.ddl.sql``.

Three modes mirror the production scenarios:

  --inserts N    : N brand-new fact rows (never seen by strata)
  --updates N    : N existing fact rows touched — ``last_updated_time``
                   advances + a non-PK field flips (forces re-ingest)
  --mixed N      : roughly half inserts, half updates

The fact table is chosen with ``--table``; the default is ``fact_pay_payment``
to preserve the original CLI shape. All four fact tables share
``last_updated_time`` as their watermark column, so the same flags work
across the board:

  --table fact_pay_payment              (default)
  --table fact_as_balance
  --table fact_as_transaction
  --table fact_as_currency_exchange

Every row written gets ``last_updated_time = NOW()`` so the next ingest's
watermark window picks it up. PKs are not specified — every fact has
``id BIGINT GENERATED BY DEFAULT AS IDENTITY``, so Postgres assigns them.

Run inside the spark container so the helper shares its venv with the
ingest job and bootstrap.py.

Usage::

    python local/scripts/add_incremental_data.py --inserts 100
    python local/scripts/add_incremental_data.py --updates 50
    python local/scripts/add_incremental_data.py --mixed 100
    python local/scripts/add_incremental_data.py --table fact_as_balance --inserts 200
    python local/scripts/add_incremental_data.py --table fact_as_transaction --mixed 500
    python local/scripts/add_incremental_data.py --table fact_as_currency_exchange --inserts 90
"""

from __future__ import annotations

import argparse
import os
import random
import sys
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

import psycopg2
from psycopg2.extras import execute_values


# ---------------------------------------------------------------------------
# Country code pool — mirrors bootstrap.py so injected rows look like seed.
# ---------------------------------------------------------------------------
COUNTRIES = [
    # (country_code, country_name, country_group_code, country_group_name, bank_bic)
    ("US", "United States",   "AMERICAS",  "Americas",              "CHASUS33"),
    ("GB", "United Kingdom",  "EU",        "Europe",                "BARCGB22"),
    ("DE", "Germany",         "EU",        "Europe",                "DEUTDEFF"),
    ("FR", "France",          "EU",        "Europe",                "BNPAFRPP"),
    ("CH", "Switzerland",     "EU_NON_EU", "Europe Non-EU",         "UBSWCHZH"),
    ("JP", "Japan",           "APAC",      "Asia Pacific",          "BOTKJPJT"),
    ("SG", "Singapore",       "APAC",      "Asia Pacific",          "DBSSSGSG"),
    ("HK", "Hong Kong",       "APAC",      "Asia Pacific",          "HSBCHKHH"),
    ("AU", "Australia",       "APAC",      "Asia Pacific",          "NATAAU33"),
    ("CA", "Canada",          "AMERICAS",  "Americas",              "ROYCCAT2"),
    ("BR", "Brazil",          "AMERICAS",  "Americas",              "BOFABRSP"),
    ("MX", "Mexico",          "AMERICAS",  "Americas",              "BNMXMXMM"),
    ("IN", "India",           "APAC",      "Asia Pacific",          "HDFCINBB"),
    ("AE", "United Arab Emirates", "MEA",  "Middle East & Africa",  "EBILAEAD"),
    ("ZA", "South Africa",    "MEA",       "Middle East & Africa",  "SBZAZAJJ"),
]

# Logical name → physical table name. Allowing lowercase + UPPERCASE means the
# CLI accepts both the strata-style logical name (FACT_PAY_PAYMENT) and the
# Postgres table name (fact_pay_payment).
TABLE_ALIASES = {
    "fact_pay_payment":          "fact_pay_payment",
    "FACT_PAY_PAYMENT":          "fact_pay_payment",
    "fact_as_balance":           "fact_as_balance",
    "FACT_AS_BALANCE":           "fact_as_balance",
    "fact_as_transaction":       "fact_as_transaction",
    "FACT_AS_TRANSACTION":       "fact_as_transaction",
    "fact_as_currency_exchange": "fact_as_currency_exchange",
    "FACT_AS_CURRENCY_EXCHANGE": "fact_as_currency_exchange",
}


# ---------------------------------------------------------------------------
# Connection + FK pool helpers
# ---------------------------------------------------------------------------

def connect():
    """Connect to the local Postgres data mart.

    Auto-detects whether we're inside the spark Docker container (uses
    the compose-network hostname ``postgres``) or running on the host
    (uses ``localhost``). Credentials and database name match the
    docker-compose defaults; override via PG* env vars.
    """
    default_host = "postgres" if os.path.exists("/.dockerenv") else "localhost"
    return psycopg2.connect(
        host=os.environ.get("PGHOST", default_host),
        port=os.environ.get("PGPORT", "5432"),
        dbname=os.environ.get("PGDATABASE", "data_mart"),
        user=os.environ.get("PGUSER", "strata"),
        password=os.environ.get("PGPASSWORD", "strata"),
    )


def fk_pools(cur) -> dict:
    """Cache the FK ID pools used across the fact-table seeders.

    Empties default to ``[1]`` rather than raising — that way the inserter
    still works against a partially-seeded data mart, even if it produces
    rows that won't join cleanly downstream.
    """
    pools: dict[str, list[int]] = {}
    for tbl in (
        "dim_account", "dim_currency", "dim_date", "dim_data_owner",
        "dim_classification", "dim_routing", "dim_as_transaction_type",
        "dim_pay_characteristics", "dim_pay_bank_status", "dim_user",
    ):
        cur.execute(f"SELECT id FROM data_mart.{tbl}")
        pools[tbl] = [r[0] for r in cur.fetchall()] or [1]
    return pools


# ---------------------------------------------------------------------------
# fact_pay_payment — inserts + updates
# ---------------------------------------------------------------------------

def _payment_row(pools: dict, now: datetime) -> tuple:
    """Build one synthetic row for fact_pay_payment (no id — IDENTITY)."""
    cc, cn, cgc, cgn, bic = random.choice(COUNTRIES)
    amt = Decimal(str(round(random.uniform(100, 500_000), 2)))
    creation = now - timedelta(
        days=random.randint(0, 30),
        seconds=random.randint(0, 86400),
    )
    return (
        random.choice(pools["dim_account"]),            # ordering_account_id
        random.randint(1, 99999),                       # requesting_execution_date
        random.choice([1, 2, 3, 4, 5]),                 # payment_method_id
        random.choice(pools["dim_currency"]),           # currency_id
        random.choice(pools["dim_data_owner"]),         # data_owner_id
        random.choice(pools["dim_classification"]),     # classification_id
        random.choice(pools["dim_pay_characteristics"]), # characteristics_id
        random.choice(pools["dim_user"]),               # first_approver_id
        random.choice(pools["dim_user"]),               # second_approver_id
        random.choice(pools["dim_pay_bank_status"]),    # bank_status_id
        random.choice(pools["dim_routing"]),            # routing_id
        amt,                                             # amount
        amt,                                             # amount_in_default_currency
        Decimal("1.0000000000"),                        # fx_rate_of_default_currency
        f"AC{random.randint(10_000_000, 99_999_999)}",  # counter_account_number
        f"Counter Bank {random.randint(1, 100)}",       # counter_bank_name
        cc, cn,                                         # counter_bank_country_*
        cc, cn, cgc, cgn,                               # counterparty_country_*
        random.randint(1, 99999),                       # own_reference_id
        random.randint(1, 9999),                        # own_reference_batch_id
        f"REF-{random.randint(1_000_000, 9_999_999)}",  # own_reference_first_id
        None, None,                                     # own_reference_second/third_id
        creation,                                       # amount_format_date
        creation + timedelta(minutes=30),               # amount_approval_date
        creation + timedelta(hours=1),                  # amount_release_date
        creation + timedelta(minutes=15),               # first_approval_date
        creation + timedelta(minutes=25),               # second_approval_date
        creation + timedelta(minutes=10),               # first_signed_date
        creation + timedelta(minutes=20),               # second_signed_date
        creation,                                       # creation_date
        random.choice(pools["dim_user"]),               # creation_user_id
        None,                                            # rejection_reason_description
        None, None, None, None, None,                   # custom_text1-5
        now,                                             # last_updated_time
    )


def insert_payments(cur, pools: dict, n: int) -> int:
    rows = []
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    for _ in range(n):
        rows.append(_payment_row(pools, now))
    execute_values(
        cur,
        """INSERT INTO data_mart.fact_pay_payment (
            ordering_account_id, requesting_execution_date,
            payment_method_id, currency_id, data_owner_id,
            classification_id, characteristics_id,
            first_approver_id, second_approver_id, bank_status_id,
            routing_id, amount, amount_in_default_currency,
            fx_rate_of_default_currency,
            counter_account_number, counter_bank_name,
            counter_bank_country_code, counter_bank_country_name,
            counterparty_country_code, counterparty_country_name,
            counterparty_country_group_code, counterparty_country_group_name,
            own_reference_id, own_reference_batch_id,
            own_reference_first_id, own_reference_second_id, own_reference_third_id,
            amount_format_date, amount_approval_date, amount_release_date,
            first_approval_date, second_approval_date,
            first_signed_date, second_signed_date,
            creation_date, creation_user_id, rejection_reason_description,
            custom_text1, custom_text2, custom_text3, custom_text4, custom_text5,
            last_updated_time
        ) VALUES %s""",
        rows,
        page_size=300,
    )
    return len(rows)


def update_payments(cur, n: int) -> int:
    """Touch N existing payments: bump last_updated_time + flip bank_status_id.

    Mirrors the realistic "the clearing bank reported a status change" path.
    Picks rows at random with no clustering so the test surface stays uniform.
    """
    cur.execute("SELECT id FROM data_mart.dim_pay_bank_status")
    bank_status_ids = [r[0] for r in cur.fetchall()] or [1]

    cur.execute(
        """SELECT id FROM data_mart.fact_pay_payment
           ORDER BY random() LIMIT %s""",
        (n,),
    )
    targets = [r[0] for r in cur.fetchall()]
    if not targets:
        return 0

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    cur.execute(
        """UPDATE data_mart.fact_pay_payment
           SET bank_status_id    = %s,
               last_updated_time = %s
           WHERE id = ANY(%s)""",
        (random.choice(bank_status_ids), now, targets),
    )
    return cur.rowcount


# ---------------------------------------------------------------------------
# fact_as_balance — inserts + updates
# ---------------------------------------------------------------------------

def insert_balances(cur, pools: dict, n: int) -> int:
    rows = []
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    for _ in range(n):
        opening = Decimal(str(round(random.uniform(10_000, 5_000_000), 2)))
        rows.append((
            random.choice(pools["dim_pay_bank_status"]),  # balance_type_id
            random.choice(pools["dim_account"]),          # account_id
            random.choice(pools["dim_currency"]),         # currency_id
            random.choice(pools["dim_date"]),             # balance_date_id
            random.choice(pools["dim_data_owner"]),       # data_owner_id
            random.choice(pools["dim_routing"]),          # routing_id
            opening,                                       # balance_amount
            opening,                                       # amount_in_default_currency
            Decimal("1.0000000000"),                      # fx_rate_of_default_currency
            date.today() - timedelta(days=random.randint(0, 30)),  # fx_rate_date
            random.randint(1, 99999),                     # statement_number
            random.randint(1, 9999),                      # sequence_number
            None, None,                                   # account_statement_id, bank_transaction_id
            None, None, None, None, None,                 # custom_text1-5
            now,                                          # last_updated_time
        ))
    execute_values(
        cur,
        """INSERT INTO data_mart.fact_as_balance (
            balance_type_id, account_id, currency_id, balance_date_id,
            data_owner_id, routing_id, balance_amount,
            amount_in_default_currency, fx_rate_of_default_currency,
            fx_rate_date, statement_number, sequence_number,
            account_statement_id, bank_transaction_id,
            custom_text1, custom_text2, custom_text3, custom_text4, custom_text5,
            last_updated_time
        ) VALUES %s""",
        rows,
        page_size=500,
    )
    return len(rows)


def update_balances(cur, n: int) -> int:
    """Touch N existing balances: bump last_updated_time + nudge balance_amount.

    Models the "end-of-day repricing changed the carried balance" scenario.
    """
    cur.execute(
        """SELECT id FROM data_mart.fact_as_balance
           ORDER BY random() LIMIT %s""",
        (n,),
    )
    targets = [r[0] for r in cur.fetchall()]
    if not targets:
        return 0

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    cur.execute(
        """UPDATE data_mart.fact_as_balance
           SET balance_amount             = balance_amount * 1.001,
               amount_in_default_currency = amount_in_default_currency * 1.001,
               last_updated_time          = %s
           WHERE id = ANY(%s)""",
        (now, targets),
    )
    return cur.rowcount


# ---------------------------------------------------------------------------
# fact_as_transaction — inserts + updates
# ---------------------------------------------------------------------------

def insert_transactions(cur, pools: dict, n: int) -> int:
    rows = []
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    for _ in range(n):
        amt = Decimal(str(round(random.uniform(10, 100_000), 2)))
        rows.append((
            random.choice(pools["dim_account"]),                # account_id
            random.choice(pools["dim_currency"]),               # currency_id
            random.choice(pools["dim_date"]),                   # value_date_id
            random.choice(pools["dim_data_owner"]),             # data_owner_id
            random.choice([0, 1]),                              # intraday_id
            random.choice(pools["dim_classification"]),         # classification_id
            random.choice(pools["dim_routing"]),                # routing_id
            random.choice(pools["dim_as_transaction_type"]),    # transaction_type_id
            amt,                                                # amount
            amt,                                                # amount_in_default_currency
            Decimal("1.0000000000"),                           # fx_rate_of_default_currency
            date.today() - timedelta(days=random.randint(0, 30)),  # fx_rate_date
            now - timedelta(seconds=random.randint(0, 86400)),     # creation_date_time
            date.today() - timedelta(days=random.randint(0, 30)),  # entry_date
            f"OWN-{random.randint(1_000_000, 9_999_999)}",      # account_owner_ref
            f"SRV-{random.randint(1_000_000, 9_999_999)}",      # account_servicer_ref
            "Incremental synthetic transaction",                # supplementary_details
            random.choice(["DBIT", "CRDT"]),                    # debit_credit_mark
            random.randint(1, 99999),                           # statement_number
            random.randint(1, 9999),                            # sequence_number
            None, None,                                         # bank_transaction_id, account_statement_id
            None, None, None, None, None,                       # custom_text1-5
            now,                                                # last_updated_time
        ))
    execute_values(
        cur,
        """INSERT INTO data_mart.fact_as_transaction (
            account_id, currency_id, value_date_id, data_owner_id,
            intraday_id, classification_id, routing_id, transaction_type_id,
            amount, amount_in_default_currency, fx_rate_of_default_currency,
            fx_rate_date, creation_date_time, entry_date,
            account_owner_ref, account_servicer_ref, supplementary_details,
            debit_credit_mark, statement_number, sequence_number,
            bank_transaction_id, account_statement_id,
            custom_text1, custom_text2, custom_text3, custom_text4, custom_text5,
            last_updated_time
        ) VALUES %s""",
        rows,
        page_size=500,
    )
    return len(rows)


def update_transactions(cur, n: int) -> int:
    """Touch N existing transactions: bump last_updated_time + flip the
    debit/credit mark.

    Models the "the bank corrected the posting direction" scenario.
    """
    cur.execute(
        """SELECT id FROM data_mart.fact_as_transaction
           ORDER BY random() LIMIT %s""",
        (n,),
    )
    targets = [r[0] for r in cur.fetchall()]
    if not targets:
        return 0

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    cur.execute(
        """UPDATE data_mart.fact_as_transaction
           SET debit_credit_mark = CASE debit_credit_mark
                                     WHEN 'DBIT' THEN 'CRDT'
                                     ELSE 'DBIT' END,
               last_updated_time = %s
           WHERE id = ANY(%s)""",
        (now, targets),
    )
    return cur.rowcount


# ---------------------------------------------------------------------------
# fact_as_currency_exchange — inserts + updates
# ---------------------------------------------------------------------------

def insert_fx_rates(cur, pools: dict, n: int) -> int:
    """Insert N FX rate observations. Each row is a (from, to) pair on
    a random recent date; same-pair duplicates are allowed since the
    natural production behaviour is multiple observations per day."""
    ccys = pools["dim_currency"]
    if len(ccys) < 2:
        return 0

    rows = []
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    for _ in range(n):
        from_id, to_id = random.sample(ccys, 2)
        rate = Decimal(str(round(random.uniform(0.1, 150.0), 10)))
        rows.append((
            random.choice(pools["dim_data_owner"]),     # data_owner_id
            random.choice(pools["dim_date"]),           # rate_date_id
            from_id, to_id, rate,                       # from/to/rate
            now,                                         # last_updated_time
        ))
    execute_values(
        cur,
        """INSERT INTO data_mart.fact_as_currency_exchange (
            data_owner_id, rate_date_id, from_currency_id, to_currency_id,
            exchange_rate, last_updated_time
        ) VALUES %s""",
        rows,
        page_size=500,
    )
    return len(rows)


def update_fx_rates(cur, n: int) -> int:
    """Touch N existing FX rates: bump last_updated_time + nudge the rate.

    Models the "intra-day re-quote" scenario.
    """
    cur.execute(
        """SELECT id FROM data_mart.fact_as_currency_exchange
           ORDER BY random() LIMIT %s""",
        (n,),
    )
    targets = [r[0] for r in cur.fetchall()]
    if not targets:
        return 0

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    nudge = Decimal("1") + Decimal(str(round(random.uniform(-0.01, 0.01), 6)))
    cur.execute(
        """UPDATE data_mart.fact_as_currency_exchange
           SET exchange_rate     = exchange_rate * %s,
               last_updated_time = %s
           WHERE id = ANY(%s)""",
        (nudge, now, targets),
    )
    return cur.rowcount


# ---------------------------------------------------------------------------
# Dispatcher — pick the right insert/update pair from --table
# ---------------------------------------------------------------------------

# Two parallel maps keep the dispatcher uniform across facts. Each tuple
# is (insert_fn, update_fn). Insert fns take pools; update fns don't.
DISPATCH = {
    "fact_pay_payment":          (insert_payments,      update_payments),
    "fact_as_balance":           (insert_balances,      update_balances),
    "fact_as_transaction":       (insert_transactions,  update_transactions),
    "fact_as_currency_exchange": (insert_fx_rates,      update_fx_rates),
}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI args. Exactly one of --inserts/--updates/--mixed is required
    so the caller's intent is explicit; ``--table`` picks the fact table
    (default ``fact_pay_payment``); ``--label`` lets you tie a batch back to
    a test name in logs; ``--seed`` makes synthetic data reproducible."""
    p = argparse.ArgumentParser(
        description="Inject incremental test data into the production-shape "
                    "data mart (any of the 4 fact tables)",
    )
    p.add_argument(
        "--table", default="fact_pay_payment",
        choices=sorted(TABLE_ALIASES.keys()),
        metavar="TABLE",
        help="Fact table to inject into. Accepts either logical (FACT_PAY_PAYMENT) "
             "or physical (fact_pay_payment) names. Default: fact_pay_payment.",
    )
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--inserts", type=int, help="N new rows")
    g.add_argument("--updates", type=int, help="N existing rows to update")
    g.add_argument("--mixed", type=int,
                   help="Total rows; ~50/50 split between inserts and updates")
    p.add_argument("--seed", type=int, default=None,
                   help="Random seed for reproducible synthetic data")
    p.add_argument("--label", default=None,
                   help="Free-form label printed to the log "
                        "(handy for tying changes to a test name)")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Inject rows into Postgres according to the chosen mode + fact table.

    Exits 0 on success. Errors propagate naturally as psycopg2 exceptions —
    there's no recovery to do because this script makes no promises beyond
    "the insert/update either committed or it didn't."
    """
    args = parse_args(argv)
    if args.seed is not None:
        random.seed(args.seed)

    table = TABLE_ALIASES[args.table]
    label = args.label or datetime.now(timezone.utc).strftime("test-%Y%m%dT%H%M%SZ")
    insert_fn, update_fn = DISPATCH[table]

    conn = connect()
    try:
        cur = conn.cursor()
        pools = fk_pools(cur)

        if args.inserts:
            n = insert_fn(cur, pools, args.inserts)
            conn.commit()
            print(f"[inserts] +{n:,} rows into data_mart.{table}  "
                  f"last_updated_time = NOW()  label={label}")
        elif args.updates:
            n = update_fn(cur, args.updates)
            conn.commit()
            print(f"[updates] ~{n:,} rows touched in data_mart.{table}  "
                  f"last_updated_time = NOW()  label={label}")
        elif args.mixed:
            half = args.mixed // 2
            n_ins = insert_fn(cur, pools, half)
            conn.commit()
            n_upd = update_fn(cur, args.mixed - half)
            conn.commit()
            print(f"[mixed]  +{n_ins:,} inserts, ~{n_upd:,} updates in "
                  f"data_mart.{table}  label={label}")
        cur.close()
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
